Repository LArSoft/larsim, pull requests merged in 2020-02, with the labels that each got.

#1 Remove unnecessary use of CreateAssn
  larsim/EventGenerator/GENIE/GENIEGen_module.cc
  larsim/EventGenerator/MARLEY/MARLEYTimeGen_module.cc
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-approved

#3 Add two github actions to move new pull requests or issues to the LArSoft pull request project
  .github/workflows/opened-issues-triage.yml
  .github/workflows/opened-pulls-triage.yml
Labels: L1-approved, code-checks-approved, new-package-pending, requires-external, signatures-pending, tests-started

#4 Fix in CORSIKAGen documentation format
  larsim/EventGenerator/CORSIKA/CORSIKAGen_module.cc
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started

#5 Add missing library dependencies
  larsim/DetSim/CMakeLists.txt
  larsim/ElectronDrift/CMakeLists.txt
  larsim/EventGenerator/CMakeLists.txt
  larsim/EventGenerator/CORSIKA/CMakeLists.txt
  larsim/EventGenerator/CRY/CMakeLists.txt
  larsim/EventGenerator/GENIE/CMakeLists.txt
  larsim/EventGenerator/MARLEY/CMakeLists.txt
  larsim/EventGenerator/MuonPropagation/CMakeLists.txt
  larsim/EventWeight/Base/CMakeLists.txt
  larsim/IonizationScintillation/CMakeLists.txt
  larsim/LArG4/CMakeLists.txt
  larsim/MCCheater/CMakeLists.txt
  larsim/MCDumpers/CMakeLists.txt
  larsim/MCSTReco/CMakeLists.txt
  larsim/MergeSimSources/CMakeLists.txt
  larsim/PhotonPropagation/CMakeLists.txt
  larsim/PhotonPropagation/LibraryMappingTools/CMakeLists.txt
  larsim/PhotonPropagation/ScintTimeTools/CMakeLists.txt
  larsim/SimFilters/CMakeLists.txt
  larsim/Simulation/CMakeLists.txt
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, requires-external, tests-started

#8 declare project language and update cmake_minimum_required
  CMakeLists.txt
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started
