Repository LArSoft/larsim, pull requests merged in 2020-06, with the labels that each got.

#20 Fix for POTaggregator module
  larsim/EventGenerator/POTaccumulator_module.cc
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started

#21 Need to set fScintillationYieldRatio member variable in Correlated alg
  larsim/IonizationScintillation/ISCalcCorrelated.cxx
Labels: L1-pending, L2-pending, code-checks-approved, signatures-pending, tests-started

#22 rhatcher fixes for redmine support issue 24283
  larsim/GDMLUtils/CMakeLists.txt
  larsim/LegacyLArG4/ConfigurablePhysicsList.icc
Labels: L1-approved, L2-approved, fully-signed, signatures-pending, tests-approved

#26 Add scintillation prescaling factor to Correlated alg
  larsim/IonizationScintillation/ISCalcCorrelated.cxx
  larsim/IonizationScintillation/ISCalcCorrelated.h
  larsim/LegacyLArG4/ISCalculationCorrelated.cxx
  larsim/LegacyLArG4/ISCalculationCorrelated.h
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started

#25 Added filtering to LightSource module based on material type.
  larsim/EventGenerator/LightSource_module.cc
Labels: L1-pending, L2-approved, code-checks-approved, fully-signed, tests-started
