Repository LArSoft/larsim, pull requests merged in 2025-08, with the labels that each got.

#156 Fix SimPhoton time rounding
  larsim/PhotonPropagation/PDFastSimPAR_module.cc
  larsim/PhotonPropagation/PDFastSimPVS_module.cc
Labels: L2-approved, code-checks-approved, L1-approved, tests-started, fully-signed

#157 Updates to semi-analytical light simulation: optical path tool
  larsim/PhotonPropagation/CMakeLists.txt
  larsim/PhotonPropagation/OpticalPathTools/CMakeLists.txt
  larsim/PhotonPropagation/OpticalPathTools/OpticalPath.h
  larsim/PhotonPropagation/OpticalPathTools/StandardOpticalPath.h
  larsim/PhotonPropagation/OpticalPathTools/StandardOpticalPath_tool.cc
  larsim/PhotonPropagation/OpticalPathTools/opticalpath_tool.fcl
  larsim/PhotonPropagation/PDFastSimPAR.fcl
  larsim/PhotonPropagation/PDFastSimPAR_module.cc
  larsim/PhotonPropagation/PDFastSimPVS_module.cc
  larsim/PhotonPropagation/PropagationTimeModel.cxx
  larsim/PhotonPropagation/PropagationTimeModel.h
  larsim/PhotonPropagation/SemiAnalyticalModel.cxx
  larsim/PhotonPropagation/SemiAnalyticalModel.h
Labels: L2-approved, requires-external, code-checks-approved, L1-approved, tests-started, fully-signed

#160 Update qalpha to 0.43
  larsim/Simulation/simulationservices.fcl
Labels: L2-approved, code-checks-approved, L1-approved, fully-signed, tests-pending
